"""Multi-platform publishing for generated videos."""

import os
from typing import Dict, Optional, Any


def _get_env_or_raise(key: str) -> str:
    value = os.getenv(key)
    if not value:
        raise ValueError(f"Environment variable {key} is required for publishing")
    return value


def publish_to_youtube(video_path: str, title: str, description: str, tags: Optional[list] = None) -> Dict[str, str]:
    """Publish a video to YouTube using OAuth2 credentials.

    Requires:
    - YOUTUBE_CLIENT_SECRETS JSON file path (YOUTUBE_CLIENT_SECRETS)
    - YOUTUBE_CREDENTIALS_JSON file path (YOUTUBE_CREDENTIALS)

    Returns a dict with keys: video_id, url
    """
    try:
        from googleapiclient.discovery import build
        from google_auth_oauthlib.flow import InstalledAppFlow
        from google.auth.transport.requests import Request
        import json
        import pickle
    except ImportError as e:
        raise ImportError("google-api-python-client and google-auth are required for YouTube publishing. Install with `pip install google-api-python-client google-auth-oauthlib`.") from e

    scopes = ["https://www.googleapis.com/auth/youtube.upload"]
    client_secrets = _get_env_or_raise("YOUTUBE_CLIENT_SECRETS")
    credentials_path = _get_env_or_raise("YOUTUBE_CREDENTIALS")

    creds = None
    if os.path.exists(credentials_path):
        with open(credentials_path, "rb") as f:
            creds = pickle.load(f)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(client_secrets, scopes)
            creds = flow.run_local_server(port=0)
        with open(credentials_path, "wb") as f:
            pickle.dump(creds, f)

    youtube = build("youtube", "v3", credentials=creds)

    body = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": tags or [],
            "categoryId": "25",  # News & Politics
        },
        "status": {"privacyStatus": "public"},
    }

    request = youtube.videos().insert(
        part=",".join(body.keys()),
        body=body,
        media_body=video_path,
    )
    response = request.execute()
    video_id = response.get("id")
    return {
        "platform": "youtube",
        "video_id": video_id,
        "url": f"https://youtu.be/{video_id}",
        "response": response,
    }


def publish_video(video: Dict[str, Any], platform: str = "youtube", **kwargs) -> Dict[str, Any]:
    """Publish a generated video to a target platform.

    Supports: youtube
    """
    path = video.get("local_path") or video.get("video_path") or video.get("video_url")
    if not path:
        raise ValueError("Video must include a local_path or video_url")

    if platform.lower() == "youtube":
        title = kwargs.get("title") or "AI News Broadcast"
        description = kwargs.get("description") or "Generated by Codexia AI News"
        tags = kwargs.get("tags") or ["AI", "News", "TrustSense"]
        return publish_to_youtube(path, title, description, tags=tags)

    raise NotImplementedError(f"Publishing to {platform} is not implemented yet")
